### ISSUE TITLE
Possible fix for Django 2.1

### ISSUE THREAD

**Issue by mikedew** [smacker/django-filebrowser-no-grappelli#56] opened 2019-06-24 07:04 UTC
I couldn't get the dev server to run django-filebrowser-no-grappelli with Django 2.1 and saw that you advertise Django 2.0 only. I made a couple of small changes in sites.py and it seems to work now with Django 2.1.9. Contributing to your project is way above my pay-grade and I don't use Git so I'll just point out what I did ...

Firstly, adopted the new Django incantation for importing re_path instead of url. Lines 207 to 210 are new. No other changes in  get_urls(). This should be OK for Django 2.2 as well with any luck.
#sites.py
205    def get_urls(self):
206        "URLs for a filebrowser.site"
207        try:
208            from django.urls import re_path as url
209        except ImportError:
210            from django.conf.urls import url
211        # filebrowser urls (views)
212        urlpatterns = [
213            url(r'^browse/$', path_exists(self, filebrowser_view(self.browse)), name="fb_browse"),

Secondly, removed self.name from the return
#sites.py
269    @property
270    def urls(self):
271        "filebrowser.site URLs"
272        return self.get_urls(), self.app_name   #, self.name

I have no idea how this may affect anything else but it works for me.

**Comment by smacker** [comment] 2019-06-28 10:22
Thank you for the bug report. Could you please attach the traceback you get while running django-filebrowser-no-grappelli without any changes?

The only known issue with django 2.1 was fixed in #44 
The tests now run on django 2.1 as well https://github.com/smacker/django-filebrowser-no-grappelli/commit/e63a3ea8e0c66bd1bf0ae83378cece9f11d18fdf

I tested it before releasing [3.7.5](https://github.com/smacker/django-filebrowser-no-grappelli/commit/1efdc5c5f3d65b28b17acac9fc9de98863649c87) and it worked for clean installation.

**Comment by smacker** [comment] 2019-12-03 19:03
As I can't reproduce the problem, I'm closing the issue. Please feel free to re-open it if you can provide more details.

**Closed by smacker** 2019-12-03 19:03 UTC
